### ISSUE TITLE
 Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited

### ISSUE THREAD

**Issue by holms** [samluescher/django-media-tree#44]
RIght after I'm doing `python manage.py collectstatic`, this happens:

```
(djangocms)djangocms@68edd942011c:/home/djangocms/djangocms# python manage.py collectstatic
/home/djangocms/djangocms/local/lib/python2.7/site-packages/media_tree/settings.py:95: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
  ('large', (400, 400)),

/home/djangocms/djangocms/local/lib/python2.7/site-packages/django/utils/datastructures.py:233: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
  return self.__class__(self)

/home/djangocms/djangocms/local/lib/python2.7/site-packages/media_tree/utils/__init__.py:3: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Traceback (most recent call last):                                                                                                                                                                                        [34/392]
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/djangocms/djangocms/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/djangocms/djangocms/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/djangocms/djangocms/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/djangocms/djangocms/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/djangocms/djangocms/local/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/home/djangocms/djangocms/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/djangocms/djangocms/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/djangocms/djangocms/local/lib/python2.7/site-packages/media_tree/admin/__init__.py", line 1, in <module>
    from media_tree.admin.filenode_admin import *
  File "/home/djangocms/djangocms/local/lib/python2.7/site-packages/media_tree/admin/filenode_admin.py", line 18, in <module>
    from media_tree.forms import FolderForm, FileForm, UploadForm
  File "/home/djangocms/djangocms/local/lib/python2.7/site-packages/media_tree/forms.py", line 9, in <module>
    class FolderForm(forms.ModelForm):
  File "/home/djangocms/djangocms/local/lib/python2.7/site-packages/django/forms/models.py", line 274, in __new__
    "needs updating." % name
django.core.exceptions.ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form FolderForm needs updating.
(djangocms)root@68edd942011c:/home/djangocms/djangocms# python manage.py collectstatic > dump
/home/djangocms/djangocms/local/lib/python2.7/site-packages/media_tree/settings.py:95: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
  ('large', (400, 400)),

/home/djangocms/djangocms/local/lib/python2.7/site-packages/django/utils/datastructures.py:233: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
  return self.__class__(self)
/home/djangocms/djangocms/local/lib/python2.7/site-packages/media_tree/utils/__init__.py:3: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/djangocms/djangocms/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/djangocms/djangocms/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/djangocms/djangocms/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/djangocms/djangocms/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/djangocms/djangocms/local/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/home/djangocms/djangocms/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/djangocms/djangocms/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/djangocms/djangocms/local/lib/python2.7/site-packages/media_tree/admin/__init__.py", line 1, in <module>
    from media_tree.admin.filenode_admin import *
  File "/home/djangocms/djangocms/local/lib/python2.7/site-packages/media_tree/admin/filenode_admin.py", line 18, in <module>
    from media_tree.forms import FolderForm, FileForm, UploadForm
  File "/home/djangocms/djangocms/local/lib/python2.7/site-packages/media_tree/forms.py", line 9, in <module>
    class FolderForm(forms.ModelForm):
  File "/home/djangocms/djangocms/local/lib/python2.7/site-packages/django/forms/models.py", line 274, in __new__
    "needs updating." % name
django.core.exceptions.ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form FolderForm needs updating.
```

Using: Django 1.8

**Comment by bittner** [comment]
I think @samluescher mentioned to use the feature branch `feature/treebeard`, which has undergone some major refactorings. Can you try whether your project runs with that branch?

**Comment by holms** [comment]
*Sigh* Would be nice to use standard package from pypi.. but ok, thanks for help. Would be nice to merge this already. Django 1.8 is stable already, I'm pretty sure tons of users expects this to work by default.

**Comment by bittner** [comment]
@holms does this mean the feature branch works for you (and Django 1.8)? Sorry, I didn't get it.

**Comment by davidkrcil** [comment]
I got the some issue today. Is there some solution to this after almost 2 years?

**Comment by holms** [comment]
@bittner i think it worked back then 💃 
@davidkrcil try that branch if that one doesn’t work than maybe it’s time to submit some PR already :)

**Comment by davidkrcil** [comment]
Thans @holms
